<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>ResponseLib</Title>
    <Authors>Ameen Al-Ya'ari</Authors>
    <Company>Tharawat</Company>
    <BaseOutputPath>C:\Users\train44\source\repos\NuGet</BaseOutputPath>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>ResponseLib</PackageId>
    <Product>ResponseLib</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="7.0.14" />
  </ItemGroup>

</Project>
